### ISSUE TITLE
Unable to instantiate activity 

### ISSUE THREAD

**Issue by BoomboomDada** [L-JINBIN/ApkSignatureKillerEx#1]
I got an error with activity no matter if enhanced on or off. this does not happen with other sig killers. I'm using MT 2.12.4

``
01-11 20:58:50.227 W/System.err( 4496): Load SignatureKiller library failed
01-11 20:58:50.362 D/AndroidRuntime( 4496): Shutting down VM
01-11 20:58:50.362 E/AndroidRuntime( 4496): FATAL EXCEPTION: main
01-11 20:58:50.362 E/AndroidRuntime( 4496): Process: com.bhvr.beyondthewall, PID: 4496
01-11 20:58:50.362 E/AndroidRuntime( 4496): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.bhvr.beyondthewall/com.bhvr.beyondthewall.Main}: java.lang.ClassNotFoundException: Didn't find class "com.bhvr.beyondthewall.Main" on path: DexPathList[[zip file "/data/app/com.bhvr.beyondthewall-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bhvr.beyondthewall-1/lib/arm, /data/app/com.bhvr.beyondthewall-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2568)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2727)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1478)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.os.Looper.loop(Looper.java:154)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.ActivityThread.main(ActivityThread.java:6121)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at java.lang.reflect.Method.invoke(Native Method)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
01-11 20:58:50.362 E/AndroidRuntime( 4496): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bhvr.beyondthewall.Main" on path: DexPathList[[zip file "/data/app/com.bhvr.beyondthewall-1/base.apk"],nativeLibraryDirectories=[/data/app/com.bhvr.beyondthewall-1/lib/arm, /data/app/com.bhvr.beyondthewall-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2558)
01-11 20:58:50.362 E/AndroidRuntime( 4496): 	... 9 more
01-11 20:58:50.365 W/ActivityManager(  516):   Force finishing activity com.bhvr.beyondthewall/.Main
```

**Comment by Darker935** [comment]
Have u tried to do KillSignature again? the same error persist?

**Comment by L-JINBIN** [comment]
Can you provide the apk file?

**Comment by ghost** [comment]
> Can you provide the apk file?

Sure, apk can be downloaded from: https://apkcombo.com/downloader/#package=com.bhvr.beyondthewall&arches=armeabi-v7a

**Comment by L-JINBIN** [comment]
It is encrypted with "网易加固", you need to decrypt it first.

**Comment by ghost** [comment]
I see, thanks
