### ISSUE TITLE
Reduce app size

### ISSUE THREAD

**Issue by Darker935** [L-JINBIN/ApkSignatureKillerEx#3]
The way the improved version of Signature Verification works is ingenious, but it has some issues.

When the user performs some modifications in the apps, their size is increased, more and more, because with each modification more data is changed, and [ApkDataMultiplexing ](https://github.com/L-JINBIN/ApkDataMultiplexing) stops being very effective.

I don't do this because this part isn't available on github, but I suggest you try to remove all the **assets/SignatureKiller/origin.apk** files, except the first **classes.dex**, and obviously **META INF**

I tried this with **SignatureKillerEx** apk from this repo, and it worked

**Comment by Darker935** [comment]
I'm talking 'bout this, cuz sometimes some apps have a very large size, and it need to be decrypted, and the size comes back close to the original

**Comment by L-JINBIN** [comment]
Many apps now check the entire apk file, and your suggestion will fail such verification.
