### ISSUE TITLE
Need documentation

### ISSUE THREAD

**Issue by ghost** [L-JINBIN/ApkSignatureKillerEx#4]
Can you make a documentation how to implement signature killer to the APK? I compiled the source then decompiled it using apktool successfully but I'm not sure how to implement it to APK afterwards

**Comment by L-JINBIN** [comment]
This project is just a demonstration of the principle of killing the signature verification function of MT Manager (mt2.cn). If you need to apply it to other apks, you need to replace origin.apk, KillerApplication.packageName, and KillerApplication.signatureData.

**Comment by ghost** [comment]
> This project is just a demonstration of the principle of killing the signature verification function of MT Manager (mt2.cn). If you need to apply it to other apks, you need to replace origin.apk, KillerApplication.packageName, and KillerApplication.signatureData.

Ok, anyway I managed to get changes made by MT by comparing both orig and modded apks
